jobs:
  main:
    requires: [ ~pr, ~commit ]
    image: node:10
    annotations:
      screwdriver.cd/manualStartEnabled: true
    steps:
      - ls

  sub:
    requires: [ ~main ]
    image: node:10
    annotations:
      screwdriver.cd/manualStartEnabled: false
    steps:
      - ls

  detatch:
    requires: [ ]
    image: node:10
    steps:
      - ls
