shared:
  image: node:14
  steps:
    - ls

jobs:
  # pattern 1
  job-commit1:
    requires: [ ~commit ]

  job-commit2:
    requires: [ ~commit ]

  job1:
    requires: [ job-commit1, job-commit2 ]

  # pattern 2
  job-tag1:
    requires: [ ~tag ]

  job-tag2:
    requires: [ ~tag ]

  job2:
    requires: [ ~job-tag1, ~job-tag2 ]

  # pattern 3
  job-release1:
    requires: [ ~release ]

  job-release2:
    requires: [ ~release ]
    
  job-release3:
    requires: [ ~release ]

  job3:
    requires: [ job-release1, job-release2, ~job-release3 ]
