shared:
  image: node:14
  steps:
    - ls

jobs:
  # pattern 1
  commit1:
    requires: [ ~commit ]

  commit2:
    requires: [ ~commit ]

  job1:
    requires: [ commit1, commit2 ]

  # pattern 2
  tag1:
    requires: [ ~tag ]

  tag2:
    requires: [ ~tag ]

  job2:
    requires: [ ~tag1, ~tag2 ]

  # pattern 3
  release1:
    requires: [ ~release ]

  release2:
    requires: [ ~release ]
    
  release3:
    requires: [ ~release ]

  job3:
    requires: [ release1, release2, ~release3 ]
