jobs:
  main:
    requires: [ ~pr, ~commit, ~commit:/test/ ]
    image: node:10
    steps:
      - step1: meta set foo 50876e6
      - step2: meta get foo

  detached:
    image: node:10
    steps:
      - echo "this is test"
