jobs:
  main:
    requires: [ ~pr, ~commit ]
    image: node:14
    steps:
      - ls

  sleep:
    requires: [ ~pr, ~commit ]
    image: node:14
    steps:
      - sleep 60
      
  joined:
    requires: [ main, sleep ]
    image: node:14
    steps:
      - ls
