annotations:
  screwdriver.cd/chainPR: true

jobs:
  main:
    requires: [ ~pr, ~commit ]
    image: node:10
    steps:
      - add-comment: meta set meta.summary.comment "Pull Request Comment"
  sub:
    requires: [ main ]
    image: node:10
    steps:
      - get-comment: meta get meta.summary.comment

